import React from 'react';
import Navbar from '../components/Navbar/Navbar';
import { ShieldCheck, Cpu, Database, Server, Key, Info, Lock } from 'lucide-react';

export default function Settings() {
  return (
    <div className="min-h-screen bg-[#F8FAFC] flex flex-col font-sans">
      <Navbar isConnected={true} />

      <main className="flex-1 max-w-4xl w-full mx-auto p-6 md:p-8 space-y-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 tracking-tight">System Settings & Security</h1>
          <p className="text-[14px] text-gray-500 mt-1">
            System configuration, sandboxed execution rules, model parameters, and database state.
          </p>
        </div>

        {/* Section 1: LLM & Inference Engine */}
        <div className="bg-white border border-gray-200 rounded-2xl p-6 shadow-xs space-y-4">
          <div className="flex items-center space-x-2 text-gray-900 font-bold text-[16px]">
            <Cpu className="w-5 h-5 text-blue-600" />
            <span>LLM & Inference Configuration</span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-[13.5px]">
            <div className="bg-gray-50 border border-gray-200 rounded-xl p-3.5">
              <span className="text-gray-500 text-[12px] font-medium uppercase">Active Model</span>
              <div className="font-bold text-gray-900 mt-1">llama-3.3-70b-versatile</div>
              <span className="text-[11.5px] text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded font-semibold mt-2 inline-block">
                Groq API Hardware Acceleration
              </span>
            </div>

            <div className="bg-gray-50 border border-gray-200 rounded-xl p-3.5">
              <span className="text-gray-500 text-[12px] font-medium uppercase">Execution Mode</span>
              <div className="font-bold text-gray-900 mt-1">Structured JSON Code Generation</div>
              <span className="text-[11.5px] text-blue-700 bg-blue-50 px-2 py-0.5 rounded font-semibold mt-2 inline-block">
                Anti-Hallucination 2-Pass Pipeline
              </span>
            </div>
          </div>
        </div>

        {/* Section 2: AST Execution Sandbox Safety */}
        <div className="bg-white border border-gray-200 rounded-2xl p-6 shadow-xs space-y-4">
          <div className="flex items-center space-x-2 text-gray-900 font-bold text-[16px]">
            <ShieldCheck className="w-5 h-5 text-emerald-600" />
            <span>AST Security & Execution Sandbox</span>
          </div>

          <p className="text-[13.5px] text-gray-600 leading-relaxed">
            All code generated by the LLM is statically validated via Python AST before execution in a restricted namespace.
          </p>

          <div className="space-y-2.5 text-[13px]">
            <div className="flex items-center justify-between bg-slate-50 p-3 rounded-lg border border-slate-200">
              <span className="font-medium text-slate-800">Import Statements Blocked</span>
              <span className="text-emerald-700 font-semibold bg-emerald-100 px-2 py-0.5 rounded text-[11.5px]">
                Enforced (ast.Import, ast.ImportFrom)
              </span>
            </div>

            <div className="flex items-center justify-between bg-slate-50 p-3 rounded-lg border border-slate-200">
              <span className="font-medium text-slate-800">Blocked System Calls</span>
              <span className="text-emerald-700 font-semibold bg-emerald-100 px-2 py-0.5 rounded text-[11.5px]">
                eval, exec, open, compile, __import__
              </span>
            </div>

            <div className="flex items-center justify-between bg-slate-50 p-3 rounded-lg border border-slate-200">
              <span className="font-medium text-slate-800">Execution Watchdog Timeout</span>
              <span className="text-blue-700 font-semibold bg-blue-100 px-2 py-0.5 rounded text-[11.5px]">
                10 Seconds Thread Limit
              </span>
            </div>

            <div className="flex items-center justify-between bg-slate-50 p-3 rounded-lg border border-slate-200">
              <span className="font-medium text-slate-800">Result Memory Cap</span>
              <span className="text-blue-700 font-semibold bg-blue-100 px-2 py-0.5 rounded text-[11.5px]">
                Max 1,000 Rows Returned
              </span>
            </div>
          </div>
        </div>

        {/* Section 3: SQLite Database & Logs */}
        <div className="bg-white border border-gray-200 rounded-2xl p-6 shadow-xs space-y-4">
          <div className="flex items-center space-x-2 text-gray-900 font-bold text-[16px]">
            <Database className="w-5 h-5 text-purple-600" />
            <span>SQLite Persistence & Logging</span>
          </div>

          <div className="bg-gray-50 p-4 rounded-xl border border-gray-200 text-[13px] space-y-2">
            <div className="flex justify-between">
              <span className="text-gray-500 font-medium">Database Path:</span>
              <span className="font-mono text-gray-800 font-semibold">logs/agent_logs.db</span>
            </div>
            <div className="flex justify-between">
              <span className="text-gray-500 font-medium">Table Schema:</span>
              <span className="font-mono text-gray-800">logs (id, timestamp, dataset_name, question, ...)</span>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
